doctrine:
    dbal:
        connections:
            default:
                driver: %database_driver%
                host: %database_host%
                user: %database_user%
                password: %database_password%
                dbname: %database_name%

ezpublish:
    repositories:
        setup: ~
    siteaccess:
        # Available siteaccesses
        list:
            - setup
        # Siteaccess groups. Use them to group common settings.
        groups: []
        default_siteaccess: setup
        match: {}

    system:
        setup:
            languages: []

stash:
    caches:
        default:
            drivers: [ BlackHole ]
            inMemory: true
            registerDoctrineAdapter: false

parameters:
    ezsettings.setup.url_alias_router: false
